//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i1_home.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public state()
        {
            this.cities_new2 = new HashSet<cities_new2>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int country_id { get; set; }
    
        public virtual ICollection<cities_new2> cities_new2 { get; set; }
        public virtual country country { get; set; }
    }
}
